title: Lourdes Nuñez # your name (or website title) here
logo: "images/1676382554967-fotor-202308141041.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
    I am a dedicated and results-driven Data Analyst and Scientist with a passion for leveraging quantitative analysis 
    to drive informed business decisions. My expertise lies in building automated, interactive reporting solutions and 
    employing advanced analytical techniques to extract actionable insights. 
    With a strong command of tools such as Tableau, SQL, Python, and proficiency in Big Data technologies (GCP, Azure) 
    I bring a comprehensive skill set to the table.
    Skills
    1) Quantitative Analysis: Proficient in employing quantitative methods to extract meaningful insights and support strategic 
    business decisions.
    2) Automated Reporting: Experienced in building automated and interactive reporting systems tailored for diverse stakeholders
    using tools like Tableau and SQL.
    3) Modeling and Projections: Adept at assisting department managers in tasks such as profit projections, system lead projections, 
    line changes, and other basic modeling tasks crucial for decision-making.
    4) Clear Communication: Able to present actionable insights in a clear and compelling manner to internal customers at all levels, 
    facilitating informed decision-making.
    5)Marketing Support: Provide robust data and reporting support to the Marketing Team, employing Python, Google Looker Studio and SQL 
    to meet their specific data requirements.
    6)Machine Learning: Proficient in building machine learning models, enhancing data-driven decision-making capabilities.
    7) Big Data and Cloud Technologies: Familiar with Big Data technologies and cloud environments such as GCP and Azure.

  <br><br>
  <a href="https://www.linkedin.com/in/lourdes-n-358153180/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-0ETDF697J6 # your Google Analytics tracking ID here
