title: Lourdes Gantz # your name (or website title) here
logo: "images/1676382554967-fotor-202308141041.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
    I am a forward-thinking AI Engineer and Researcher specialized in generative AI and 
    intelligent system design. My passion lies in building scalable, AI-driven applications 
    and platforms that automate workflows, generate novel content. 
    I bring deep expertise in deploying cutting-edge models and creating robust backend pipelines
    using Python, cloud infrastructure (GCP, Azure), and MLOps practices. 

  <br><br>
  <a href="https://www.linkedin.com/in/lourdes-n-358153180/">View My LinkedIn Profile</a>

  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-0ETDF697J6 # your Google Analytics tracking ID here
