title: Lourdes Nuñez # your name (or website title) here
logo: "images/1676382554967-fotor-202308141041.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
    I am a dedicated and results-driven Data Analyst and Scientist with a passion for leveraging quantitative analysis 
    to drive informed business decisions. My expertise lies in building automated, interactive reporting solutions and 
    employing advanced analytical techniques to extract actionable insights. 
    With a strong command of tools such as Tableau, SQL, Python, Machine learning and Big Data technologies (GCP, Azure) 
    

  <br><br>
  <a href="https://www.linkedin.com/in/lourdes-n-358153180/">View My LinkedIn Profile</a> 
  <a href="https://github.com/datalou">View My Github Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-0ETDF697J6 # your Google Analytics tracking ID here
